### ISSUE TITLE
We need to iterate all the collision pairs, not just the first one

### ISSUE THREAD

**Issue by imini-app** [imini-app/phaser-examples#22]
https://github.com/imini-app/phaser-examples/blob/c45aac88cd053fd4320049573c08abe4ed9dcd30/src/games/platformer/Scene.js#L268

When `collisionStart` happens, we may have multiple pairs. Right now, we only process the first item.

So we need to do a loop
```js
for (const pair of event.pairs) {
  processLogic(pair)
}

processLogic(pair) {
// the current processing logic in the collision start
}
```

**Comment by xwillxu** [comment]
Fixed with this pr: https://github.com/imini-app/phaser-examples/pull/23
